#!/bin/sh
#
# Load maia-sdr kernel module
#

case "$1" in
  start)
	echo -n "Loading maia-sdr.ko: "
	insmod /lib/modules/maia-sdr.ko
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
